{{- $image := include "managed-serviceaccount-common.agentImage" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-serviceaccount-addon-agent
  namespace: {{ .Values.addonInstallNamespace }}
{{- if eq .Values.installMode "Hosted" }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      addon-agent: managed-serviceaccount
  template:
    metadata:
      labels:
        addon-agent: managed-serviceaccount
    spec:
{{- if eq .Values.installMode "Hosted" }}
      serviceAccountName: managed-serviceaccount
{{- else }}
      serviceAccountName: {{ .Values.ManagedServiceAccountName }}
{{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- if .Values.NodeSelector }}
      nodeSelector: {{ toYaml .Values.NodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.Tolerations }}
      tolerations: {{ toYaml .Values.Tolerations | nindent 8 }}
{{- end }}
      containers:
        - name: addon-agent
          image: {{ $image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - ALL
          command:
            - /msa
            - agent
          args:
            - --leader-elect=false
            - --cluster-name={{ .Values.clusterName }}
            - --install-mode={{ .Values.installMode }}
            - --kubeconfig=/etc/hub/kubeconfig
{{- if eq .Values.installMode "Hosted" }}
            - --spoke-kubeconfig=/etc/managed/kubeconfig
{{- end }}
            - --lease-health-check=true
          ports:
            - name: metrics
              containerPort: 38080
              protocol: TCP
          volumeMounts:
            - name: hub-kubeconfig
              mountPath: /etc/hub/
              readOnly: true
{{- if eq .Values.installMode "Hosted" }}
            - name: managed-kubeconfig
              mountPath: /etc/managed/
              readOnly: true
{{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 10
      volumes:
        - name: hub-kubeconfig
          secret:
            secretName: {{ .Values.hubKubeConfigSecret }}
{{- if eq .Values.installMode "Hosted" }}
        - name: managed-kubeconfig
          secret:
            secretName: {{ .Values.ManagedKubeConfigSecret }}
{{- end }}
{{- if .Values.imagePullSecretData }}
      imagePullSecrets:
      - name: open-cluster-management-image-pull-credentials
{{- end }}
