{{- if .Values.imagePullSecretData }}
apiVersion: v1
kind: Secret
metadata:
  name: open-cluster-management-image-pull-credentials
  namespace: {{ .Values.addonInstallNamespace }}
{{- if eq .Values.installMode "Hosted" }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
{{- end }}
type: kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{ .Values.imagePullSecretData }}
{{- end }}
