{{- if .Values.imagePullSecretData }}
apiVersion: v1
kind: Secret
metadata:
  name: open-cluster-management-image-pull-credentials
  namespace: {{ .Values.addonInstallNamespace }}
type: kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{ .Values.imagePullSecretData }}
{{- end }}
