{{- if eq .Values.installMode "Hosted" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: managed-serviceaccount-health-lease
  namespace: {{ .Values.addonInstallNamespace }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "patch"]
{{- end }}
