apiVersion: v1
kind: Service
metadata:
  name: managed-serviceaccount-addon-agent
  namespace: {{ .Values.addonInstallNamespace }}
  labels:
    addon-agent: managed-serviceaccount
spec:
  selector:
    addon-agent: managed-serviceaccount
  ports:
    - name: metrics
      port: 38080
      targetPort: metrics
      protocol: TCP
