{{- if eq .Values.installMode "Hosted" }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: managed-serviceaccount-kubeconfig-provisioner
  namespace: {{ .Values.addonInstallNamespace }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
{{- end }}
