{{- if eq .Values.installMode "Hosted" }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-serviceaccount-kubeconfig-provisioner
  namespace: {{ .Values.addonInstallNamespace }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: managed-serviceaccount-kubeconfig-provisioner
subjects:
  - kind: ServiceAccount
    name: managed-serviceaccount-kubeconfig-provisioner
    namespace: {{ .Values.addonInstallNamespace }}
{{- end }}
