{{- if .Values.Prometheus.Enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: managed-serviceaccount-addon-agent
  namespace: {{ .Values.addonInstallNamespace }}
{{- if eq .Values.installMode "Hosted" }}
  annotations:
    addon.open-cluster-management.io/hosted-manifest-location: hosting
{{- end }}
{{- with .Values.Prometheus.ServiceMonitor.Labels }}
  labels:
{{- range $key, $value := . }}
    {{ printf "%q" $key }}: {{ printf "%q" $value }}
{{- end }}
{{- end }}
spec:
  endpoints:
    - path: /metrics
      scheme: http
      port: metrics
  selector:
    matchLabels:
      addon-agent: managed-serviceaccount
{{- end }}
