apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  namespace: CLUSTER_NAME
spec:
  installNamespace: open-cluster-management-managed-serviceaccount
