apiVersion: authentication.open-cluster-management.io/v1beta1
kind: ManagedServiceAccount
metadata:
  name: ttl-demo
  namespace: CLUSTER_NAME
  finalizers:
  - "prevent-deletion-for-demo"
spec: 
  rotation: 
    enabled: true
    validity: 8640h0m0s
  ttlSecondsAfterCreation: 5
