apiVersion: addon.open-cluster-management.io/v1beta1
kind: AddOnDeploymentConfig
metadata:
  name: managed-serviceaccount
  namespace: CLUSTER_NAME
spec:
  agentInstallNamespace: open-cluster-management-managed-serviceaccount
---
apiVersion: addon.open-cluster-management.io/v1beta1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  namespace: CLUSTER_NAME
spec:
  configs:
  - group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
    namespace: CLUSTER_NAME
    name: managed-serviceaccount
