coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        target: auto
        threshold: 1%

ignore:
  - "**/*generated*.go"
# Test coverage is not required for generated files