FROM golang:1.25-bookworm AS builder
ARG OS=linux
ARG ARCH=amd64
WORKDIR /go/src/github.com/open-cluster-management.io/managed-serviceaccount
COPY . .
RUN go env
RUN GOOS=${OS} GOARCH=${ARCH} CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -a -o bin/cp-creds cmd/clusterprofile-credentials-plugin/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
COPY --from=builder /go/src/github.com/open-cluster-management.io/managed-serviceaccount/bin/cp-creds /
