apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: managed-serviceaccount-agent-metrics
  namespace: loopback
spec:
  customizedVariables:
  - name: AgentServiceMonitorEnabled
    value: "true"
  # Labels are parsed as comma-separated key=value pairs.
  - name: AgentServiceMonitorLabels
    value: "release=prometheus"
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  namespace: loopback
spec:
  installNamespace: open-cluster-management-agent-addon
  configs:
  - group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
    namespace: loopback
    name: managed-serviceaccount-agent-metrics
