kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:managed-serviceaccount:addon-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:managed-serviceaccount:addon-agent
subjects:
  - kind: ServiceAccount
    name: managed-serviceaccount
    namespace: {{ .AddonInstallNamespace }}
