apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-serviceaccount-addon-agent
  namespace: {{ .AddonInstallNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      addon-agent: managed-serviceaccount
  template:
    metadata:
      labels:
        addon-agent: managed-serviceaccount
    spec:
      serviceAccount: managed-serviceaccount
      containers:
        - name: addon-agent
          image: {{ .Image }}
          imagePullPolicy: IfNotPresent
          command:
            - /agent
          args:
            - --leader-elect=true
            - --cluster-name={{ .ClusterName }}
            - --kubeconfig=/etc/hub/kubeconfig
          volumeMounts:
            - name: hub-kubeconfig
              mountPath: /etc/hub/
              readOnly: true
      volumes:
        - name: hub-kubeconfig
          secret:
            secretName: managed-serviceaccount-hub-kubeconfig
{{ if .ImagePullSecretData }}
      imagePullSecrets:
      - name: open-cluster-management-image-pull-credentials
{{- end }}
