apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-serviceaccount-addon-agent
  namespace: {{ .AddonInstallNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      addon-agent: managed-serviceaccount
  template:
    metadata:
      labels:
        addon-agent: managed-serviceaccount
    spec:
      serviceAccount: managed-serviceaccount
{{- if .NodeSelector }}
      nodeSelector:
      {{- range $key, $value := .NodeSelector }}
        "{{ $key }}": "{{ $value }}"
      {{- end }}
{{- end }}
{{- if .Tolerations }}
      tolerations:
      {{- range $toleration := .Tolerations }}
      - key: "{{ $toleration.Key }}"
        value: "{{ $toleration.Value }}"
        effect: "{{ $toleration.Effect }}"
        operator: "{{ $toleration.Operator }}"
        {{- if $toleration.TolerationSeconds }}
        tolerationSeconds: {{ $toleration.TolerationSeconds }}
        {{- end }}
      {{- end }}
{{- end }}
      containers:
        - name: addon-agent
          image: {{ .Image }}
          imagePullPolicy: IfNotPresent
          command:
            - /agent
          args:
            - --leader-elect=true
            - --cluster-name={{ .ClusterName }}
            - --kubeconfig=/etc/hub/kubeconfig
          volumeMounts:
            - name: hub-kubeconfig
              mountPath: /etc/hub/
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 10
      volumes:
        - name: hub-kubeconfig
          secret:
            secretName: managed-serviceaccount-hub-kubeconfig
{{ if .ImagePullSecretData }}
      imagePullSecrets:
      - name: open-cluster-management-image-pull-credentials
{{- end }}
