# should not overwrite the pull secret if it is the default namespace
{{ if ne .AddonInstallNamespace "open-cluster-management-agent-addon" }}
{{ if .ImagePullSecretData }}
apiVersion: v1
kind: Secret
metadata:
  name: open-cluster-management-image-pull-credentials
  namespace: {{ .AddonInstallNamespace }}
type:  kubernetes.io/dockerconfigjson
data:
  ".dockerconfigjson": {{ .ImagePullSecretData }}
{{ end }}
{{ end }}
