apiVersion: v1
kind: Namespace
metadata:
  name: {{ .AddonInstallNamespace }}
{{ if eq .AddonInstallNamespace "open-cluster-management-agent-addon" }}
  annotations:
    addon.open-cluster-management.io/deletion-orphan: ""
  labels:
    addon.open-cluster-management.io/namespace: "true"
{{ end }}
