apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: open-cluster-management:managed-serviceaccount:addon-agent
  namespace: {{ .AddonInstallNamespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts", "serviceaccounts/token"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenrequests"]
  verbs: ["get", "create", "update", "patch"]
