{{- if eq .Values.hubDeployMode "AddOnTemplate" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managed-serviceaccount-addon-agent
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - authentication.open-cluster-management.io
  resources:
  - managedserviceaccounts
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - authentication.open-cluster-management.io
  resources:
  - managedserviceaccounts/status
  verbs:
  - get
  - update
  - patch
{{- end }}
