apiVersion: addon.open-cluster-management.io/v1beta1
kind: ClusterManagementAddOn
metadata:
  name: managed-serviceaccount
spec:
  addOnMeta:
    displayName: managed-serviceaccount
    description: managed-serviceaccount
{{- if .Values.agentInstallAll }}
  installStrategy:
    placements:
    - name: global
      namespace: {{ .Release.Namespace }}
      rolloutStrategy:
        type: All
    type: Placements
{{- end }}
