apiVersion: addon.open-cluster-management.io/v1beta1
kind: ClusterManagementAddOn
metadata:
  name: managed-serviceaccount
{{- if eq .Values.hubDeployMode "AddOnTemplate" }}
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
{{- end }}
spec:
  addOnMeta:
    displayName: managed-serviceaccount
    description: managed-serviceaccount
{{- if .Values.agentInstallAll }}
  installStrategy:
    placements:
    - name: global
      namespace: {{ .Release.Namespace }}
      rolloutStrategy:
        type: All
    type: Placements
{{- end }}
{{- if eq .Values.hubDeployMode "AddOnTemplate" }}
  defaultConfigs:
  - group: addon.open-cluster-management.io
    resource: addontemplates
    name: {{ .Values.addOnTemplateName | default (print "managed-serviceaccount-" .Chart.Version) }}
{{- end }}
