apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: managed-serviceaccount-addon-manager
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      open-cluster-management.io/addon: managed-serviceaccount
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: managed-serviceaccount
    spec:
      serviceAccount: managed-serviceaccount
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: {{ .Values.image }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - ALL
          command:
            - /msa
            - manager
          args:
            {{- if gt (int .Values.replicas) 1 }}
            - --leader-elect=true
            {{- end }}
            - --metrics-bind-address=:38080
            - --agent-image-name={{ .Values.image }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
            {{- if .Values.featureGates }}
            - --feature-gates=EphemeralIdentity={{ .Values.featureGates.ephemeralIdentity | default false}},ClusterProfile={{ .Values.featureGates.clusterProfile | default false}}
            {{- end }}
            {{- if .Values.agentImagePullSecret }}
            - --agent-image-pull-secret={{ .Values.agentImagePullSecret }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: 38080
              protocol: TCP
