{{ if .Values.targetCluster }}
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  namespace: {{ .Values.targetCluster }}
spec:
{{ if eq .Values.hubDeployMode "AddOnTemplate" }}
  installNamespace: "open-cluster-management-agent-addon"
{{ else }}
  installNamespace: "open-cluster-management-managed-serviceaccount"
{{ end }}
{{ end }}
