{{- if .Values.targetCluster }}
apiVersion: addon.open-cluster-management.io/v1beta1
kind: AddOnDeploymentConfig
metadata:
  name: managed-serviceaccount
  namespace: {{ .Values.targetCluster }}
spec:
  agentInstallNamespace: open-cluster-management-managed-serviceaccount
---
apiVersion: addon.open-cluster-management.io/v1beta1
kind: ManagedClusterAddOn
metadata:
  name: managed-serviceaccount
  namespace: {{ .Values.targetCluster }}
spec:
  configs:
  - group: addon.open-cluster-management.io
    resource: addondeploymentconfigs
    namespace: {{ .Values.targetCluster }}
    name: managed-serviceaccount
{{- end }}
