{{- if or (ne .Values.hubDeployMode "AddOnTemplate") .Values.featureGates.clusterProfile }}
apiVersion: v1
kind: Service
metadata:
  name: managed-serviceaccount-addon-manager-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    open-cluster-management.io/addon: managed-serviceaccount
spec:
  selector:
    open-cluster-management.io/addon: managed-serviceaccount
  ports:
    - name: metrics
      port: {{ .Values.metrics.port | default 38080 }}
      targetPort: metrics
      protocol: TCP
{{- end }}
