{{- if not .Values.installByPlacement.placementName }}
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name:  managed-serviceaccount-placement
  namespace:  {{ .Release.Namespace }}
spec:
  clusterSets:
    - global
{{- end }}
