apiVersion: authentication.open-cluster-management.io/v1beta1
kind: ManagedServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: managedserviceaccount
    app.kubernetes.io/instance: managedserviceaccount-sample
    app.kubernetes.io/part-of: managed-serviceaccount
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: managed-serviceaccount
  name: managedserviceaccount-sample
spec:
  # TODO(user): Add fields here
