apiVersion: authentication.open-cluster-management.io/v1alpha1
kind: ManagedServiceAccount
metadata:
  name: cluster-gateway
  namespace: vela-dev
spec:
  projected:
    type: Secret
    secret:
      namespace: open-cluster-management-credentials
      name: vela-dev
      labels:
        cluster.core.oam.dev/cluster-credential-type: ServiceAccountToken
        cluster.core.oam.dev/cluster-endpoint-type: ClusterProxy
  rotation: {}
