name: GoPostSubmit

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.16'
  GO_REQUIRED_MIN_VERSION: ''
  GOPATH: '/home/runner/work/managed-serviceaccount/managed-serviceaccount/go'
defaults:
  run:
    working-directory: go/src/open-cluster-management.io/managed-serviceaccount

jobs:
  verify:
    name: latest-images
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/managed-serviceaccount
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: image
        run: make image
      - name: push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push quay.io/open-cluster-management/managed-serviceaccount:latest